### PR TITLE
Fix issue #144 + Fix some field not being retreived as they should

### LINKED ISSUE #144: Following PR #143, some issues and/or code quality adjustments remains
### Issue  

Isn't `matter_id` Laravel's implicit key for that relationship? Why make it explicit?  

_Originally posted by @jjdejong in https://github.com/jjdejong/phpip/pull/143#discussion_r1929824010_  

AND  

Why make that key explicit?  

_Originally posted by @jjdejong in https://github.com/jjdejong/phpip/pull/143#discussion_r1929824150_  

### Answer  

Sometimes, the static `getLocalKey` method throws an error when keys aren’t explicitly declared. Although Laravel computes the key automatically, I’ve encountered this issue multiple times. That’s why I now prefer to explicitly specify the key.  

Additionally, even if the key is obvious, explicitly declaring it makes the code more readable. This way, we can identify the key directly from the code without needing to inspect the database.  

---

### Issue  

How does this conditional `$request` definition play in terms of query building? This doesn't look SQL optimization friendly—it would generate two database queries. However, optimization is probably not crucial here since we are doing it for a single matter.  

Apart from that, this should return all actors, those from the current matter plus those from the container matter if shared. In SQL, this would need to be translated as a `UNION ALL`, so a `->merge()` here.  

_Originally posted by @jjdejong in https://github.com/jjdejong/phpip/pull/143#discussion_r1929833659_  

AND  

This issue remains, though, which appears to need the use of a `->merge()` or an `->orWhere`:  

> Apart from that, this should return all actors, those from the current matter plus those from the container matter if shared. In SQL, this would need to be translated as a `UNION ALL`, so a `->merge()` here.  

_Originally posted by @jjdejong in https://github.com/jjdejong/phpip/pull/143#discussion_r1930101240_  

### Answer  

In my opinion, the `hasOneActorThroughActorPivot` method doesn’t need to be modified to include a `->merge` since we are expecting only one result.  
- If the result isn’t found using the `matter.id` request, it will fall back to the `matter.container_id` request.  
- If the `matter.container_id` request also doesn’t return a result, it will simply return `null`, which aligns with our expectations.  

Do we agree that the actors from the current matter should take precedence over those from `matter.container_id`?  

That said, the `belongsToManyActors` method does need modification, as you correctly pointed out. It should return all actors related to the matter, regardless of whether they come from `matter.id` or `matter.container_id`. Unfortunately, Laravel doesn’t natively support using `UNION ALL` in relationships, and none of my attempts to make it work have been successful.  

To address this, we might need to use a `->merge()` with an Eloquent query like `Actor::query()` or `$this->actors()`. However, doing so will disable eager loading.  

### Additional Considerations  

The `hasOneActorThroughActorPivot` method could be rewritten to use a `->first()` on the `belongsToManyActors`. However, this would also result in losing eager loading. Additionally:  
- We’d need to call the method (`->agent()`) instead of using the magic property (`->agent`), which is less intuitive and, in my opinion, less elegant.  
- To avoid this, I could create a `get{ActorRoleName}Attribute` accessor, which would eliminate the need for method calls. But this would require writing a significant amount of extra code for minimal gain.  

Let me know your thoughts on this approach!

### PR DESCRIPTION
**Pull request by AxelDeneu**
Fixes #144

### CODE REVIEW

File: app/Traits/HasActorsFromRole.php [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+     */
+    public function getActorsFromRole(string $role): \Illuminate\Database\Eloquent\Collection
+    {
+        return Actor::query()
+            ->join('matter_actor_lnk', 'actor.id', '=', 'matter_actor_lnk.actor_id')
+            ->where('matter_actor_lnk.role', $role)
+            ->where(function ($query) {
+                $query
+                    ->where('matter_actor_lnk.matter_id', $this->id)
+                    ->orWhere('matter_actor_lnk.matter_id', $this->container_id);
```
Comment (jjdejong) [inline app/Traits/HasActorsFromRole.php]: Forgot the condition shared = 1 for the actor from the container to be returned.

**Review by jjdejong — CHANGES_REQUESTED** [review]
I realize now that I forgot to mention the presence of the MatterActors model based on the view matter_actors that is supposed to hide the container and actor sharing complexity - it basically provides an "effective" pivot table. I failed to construct the same logic efficiently with relationships, and Claude ended up concluding that using a view was better in terms of performance and code readability. I've been using MatterActors instead of ActorPivot since the beginning! Of course, the use of a view precludes any write access to the model.

**Comment by AxelDeneu** [comment]
I'm not a big fan of views. While they do offer better performance, they don’t really help with readability. As you mentioned, you also lose write access, which isn’t ideal.  

Additionally, understanding the structure and creation of a view requires reading through the SQL declaration, which can be quite tedious. With Laravel, you typically don’t need to create views in your database because a well-written SQL schema using models and migrations should suffice.  

If we were to "recreate the wheel," the "container" concept shouldn’t be designed this way. Instead, it would make more sense to work on the `Matter` class and define a proper parent-child relationship. That way, all related actors could be logically grouped under the parent or child, making it much easier to retrieve actors from children or all related matters.  

For now, I’ve used the `matter_actor_lnk` table without the view because it aligns better with my understanding of the phpIP database. However, I can change this if you’d prefer.

File: app/Traits/HasActorsFromRole.php (hunk 1 above)
Comment (AxelDeneu) [reply app/Traits/HasActorsFromRole.php]: Yep, that's my bad. I'm fixing this.

**Comment by jjdejong** [comment]
> I'm not a big fan of views. While they do offer better performance, they don’t really help with readability. As you mentioned, you also lose write access, which isn’t ideal.

I'm not either, but this one is an exception. It implements all the container and sharing logic behind the scene, greatly simplifying the Laravel logic, so readability, no? Plus it has an `inherited` flag indicating that the data is a copy from the container (for displaying it differently in the UI, for instance). 

When writing is required, this is done via ActorPivot. Maybe the create and update functionality in MatterActor can be "diverted" to ActorPivot to make this transparent.

> Additionally, understanding the structure and creation of a view requires reading through the SQL declaration, which can be quite tedious. With Laravel, you typically don’t need to create views in your database because a well-written SQL schema using models and migrations should suffice.

The view is not that complex and, in this particular case, we can't get the same performance and ease of use with pure Laravel. The view was really designed to hide this complexity.

> If we were to "recreate the wheel," the "container" concept shouldn’t be designed this way. Instead, it would make more sense to work on the `Matter` class and define a proper parent-child relationship. That way, all related actors could be logically grouped under the parent or child, making it much easier to retrieve actors from children or all related matters.

The container concept was designed back in 2011 way before migrating to Laravel and with a much less flexible MVC at the time (Zend Framework v1). It was designed to avoid what other products did, by providing a "family" table containing all the common information to a patent family, to which individual patents were later linked, with additional information. This  complicated the table structure and reduced flexibility, because you couldn't define different actors for different patents in the same family.  In other products with a "family" table, to make things more flexible, the individually created patents copied all the information from the family, uselessly duplicating all this information and causing out of sync errors when common data needed to be modified. Moreover, I put a lot of intelligence in the db itself around this concept with extensive use of triggers and stored procedures. 

How would you define such a "proper" parent-child relationship without a field in the child that identifies the parent like `container_id`? (Note that we also have `parent_id` in a matter, for parent-child relationships specific to patents...)

> For now, I’ve used the `matter_actor_lnk` table without the view because it aligns better with my understanding of the phpIP database. However, I can change this if you’d prefer.

No urgency, since this would break a lot of the code you've contributed, and I apologize for not reacting earlier. Yet, using the `matter_actors` view instead would make things more consistent with what I've done elsewhere.
